sonar.organization=sira-exe
sonar.projectKey=Sira-exe_DontEverPushThisCodeV2
sonar.projectName=DontEverPushThisCodeV2
sonar.sources=app,components,lib,pages
sonar.exclusions=node_modules/**,.next/**,reports/**
